global:
  oss:
    bucket: &default-oss-bucket "arcadia"

# @section controller is used as the core controller for arcadia
# @param image Image to be used
# @param imagePullPolcy ImagePullPolicy
# @param resources Resources to be used
controller:
  image: kubeagi/arcadia:v0.1.0-20240105-2833016
  imagePullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 10m
      memory: 64Mi

# @section graphql and bff server
# related project: https://github.com/kubeagi/arcadia/tree/main/apiserver
apiserver:
  image: kubeagi/arcadia:v0.1.0-20240105-2833016
  enableplayground: false
  port: 8081
  ingress:
    enabled: true
    path: kubeagi-apis
    host: portal.<replaced-ingress-nginx-ip>.nip.io
  oidc:
    enabled: true
    clientID: bff-client
    clientSecret: 61324af0-1234-4f61-b110-ef57013267d6
    issuerURL: https://portal.<replaced-ingress-nginx-ip>.nip.io/oidc
    masterURL: https://k8s.<replaced-ingress-nginx-ip>.nip.io

# @section portal for arcadia web console
portal:
  enabled: true
  kubebbEnabled: true
  image: kubeagi/ops-console:v0.1.0-20240105-6658717
  port: 80
  ingress:
    path: kubeagi-portal-public
    host: portal.<replaced-ingress-nginx-ip>.nip.io

# @section fastchat is used as fastchat configurations for arcadia
fastchat:
  image:
    repository: kubeagi/arcadia-fastchat
    # Use either v0.1.0
    tag: v0.1.0
  ingress:
    enabled: true
    host: fastchat-api.<replaced-ingress-nginx-ip>.nip.io

# @section oss is used as default Object-Storage-Service for arcadia
minio:
  image:
    repository: kubeagi/minio
    tag: RELEASE.2023-02-10T18-48-39Z
  mode: standalone
  rootUser: "admin"
  rootPassword: "Passw0rd!"
  persistence:
    enabled: true
    storageClass: "openebs-hostpath"
    size: 30Gi
  ingress:
    enabled: true
    api:
      enabled: true
      insecure: false
      port: 9000
      host: minio-api.<replaced-ingress-nginx-ip>.nip.io
    console:
      enabled: false
      port: 9001
      host: minio-console.<replaced-ingress-nginx-ip>.nip.io
    cert:
      ipAddresses:
      - <replaced-ingress-nginx-ip>
      dnsNames:
      - minio-api.<replaced-ingress-nginx-ip>.nip.io
      - minio-console.<replaced-ingress-nginx-ip>.nip.io
  buckets:
    # Name of the bucket
    - name: *default-oss-bucket
      # Policy to be set on the
      # bucket [none|download|upload|public|custom]
      # if set to custom, customPolicy must be set.
      policy: "none"
      # set versioning for
      # bucket [true|false]
      versioning: false
      # set objectlocking for
      # bucket [true|false] NOTE: versioning is enabled by default if you use locking
      objectlocking: false

# @section chromadb is used to deploy a chromadb instance
chromadb:
  image:
    repository: kubeagi/chromadb
  chromadb:
    apiVersion: "0.4.18"
    auth:
      enabled: false
    serverHttpPort: 8000
    dataVolumeStorageClass: "openebs-hostpath"
    dataVolumeSize: "1Gi"

# @section dataprocess is used to configure data processing service
# Related project: https://github.com/kubeagi/arcadia/tree/main/data-processing
dataprocess:
  enabled: true
  image: kubeagi/data-processing:v0.1.0-20240104-ecfe3f0
  port: 28888
  config:
    llm:
      qa_retry_count: '2'

# @section postgresql is used to configure postgresql service
# Posgresql service will be used in two parts:
# - dataprocessing
# - llm application
# - used as vector store with pgvector enabled
postgresql:
  enabled: true
  global:
    storageClass: "openebs-hostpath"
    postgresql:
      auth:
        # default username and password
        username: "admin"
        password: "Passw0rd!"
        # default database
        database: "arcadia"
  # image configurations
  image:
    registry: docker.io
    repository: kubeagi/postgresql
    tag: 16.1.0-debian-11-r15
    pullPolicy: IfNotPresent
  primary:
    initdb:
      scriptsConfigMap: pg-init-data
