apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - deployments/status
  verbs:
  - get
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - pods
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims/status
  - pods/status
  - services/status
  verbs:
  - get
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - agents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - agents/finalizers
  verbs:
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - agents/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - applications/finalizers
  verbs:
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - applications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - datasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - datasets/finalizers
  verbs:
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - datasets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - datasources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - datasources/finalizers
  verbs:
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - datasources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - documentloaders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - documentloaders/finalizers
  verbs:
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - documentloaders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - embedders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - embedders
  - llms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - embedders/finalizers
  verbs:
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - embedders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - embedders/status
  - llms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - knowledgebases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - knowledgebases/finalizers
  verbs:
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - knowledgebases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - llms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - llms/finalizers
  verbs:
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - llms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - models
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - models/finalizers
  verbs:
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - models/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - prompts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - prompts/finalizers
  verbs:
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - prompts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - vectorstores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - vectorstores/finalizers
  verbs:
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - vectorstores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - versioneddataset
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - versioneddataset/status
  verbs:
  - get
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - versioneddatasets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - versioneddatasets/finalizers
  verbs:
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - versioneddatasets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - workers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - workers/finalizers
  verbs:
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - workers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - '*'
- apiGroups:
  - chain.arcadia.kubeagi.k8s.com.cn
  resources:
  - apichains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - chain.arcadia.kubeagi.k8s.com.cn
  resources:
  - apichains/finalizers
  verbs:
  - update
- apiGroups:
  - chain.arcadia.kubeagi.k8s.com.cn
  resources:
  - apichains/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - chain.arcadia.kubeagi.k8s.com.cn
  resources:
  - llmchains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - chain.arcadia.kubeagi.k8s.com.cn
  resources:
  - llmchains/finalizers
  verbs:
  - update
- apiGroups:
  - chain.arcadia.kubeagi.k8s.com.cn
  resources:
  - llmchains/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - chain.arcadia.kubeagi.k8s.com.cn
  resources:
  - retrievalqachains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - chain.arcadia.kubeagi.k8s.com.cn
  resources:
  - retrievalqachains/finalizers
  verbs:
  - update
- apiGroups:
  - chain.arcadia.kubeagi.k8s.com.cn
  resources:
  - retrievalqachains/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - evaluation.arcadia.kubeagi.k8s.com.cn
  resources:
  - rags
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - evaluation.arcadia.kubeagi.k8s.com.cn
  resources:
  - rags/finalizers
  verbs:
  - update
- apiGroups:
  - evaluation.arcadia.kubeagi.k8s.com.cn
  resources:
  - rags/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - prompt.arcadia.kubeagi.k8s.com.cn
  resources:
  - prompts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - prompt.arcadia.kubeagi.k8s.com.cn
  resources:
  - prompts/finalizers
  verbs:
  - update
- apiGroups:
  - prompt.arcadia.kubeagi.k8s.com.cn
  resources:
  - prompts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - get
  - list
  - update
- apiGroups:
  - retriever.arcadia.kubeagi.k8s.com.cn
  resources:
  - knowledgebaseretrievers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - retriever.arcadia.kubeagi.k8s.com.cn
  resources:
  - knowledgebaseretrievers/finalizers
  verbs:
  - update
- apiGroups:
  - retriever.arcadia.kubeagi.k8s.com.cn
  resources:
  - knowledgebaseretrievers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
