apiVersion: agent.arcadia.kubeagi.k8s.com.cn/v1alpha1
kind: Agent
metadata:
  name: weather-agent
  namespace: test
spec:
  type: zeroShot
  allowedTools:
  - name: "Weather Query API"
    parms:
      apiKey: <api key to use>
  options:
    maxIterations: 5
